import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from './../styles/Home.module.css'
import { ProductCard } from './components/productCard'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Frontend Mentor | Product preview card component</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/png" sizes="32x32" href="./images/favicon-32x32.png" />
      </Head>
      <main className={styles.main}>
        <ProductCard></ProductCard>
      </main>
    </>
  )
}
